### ISSUE TITLE
Interference Of the Signal Generator App 

### ISSUE THREAD

**Issue by beckysophie** [billthefarmer/sig-gen#15] opened 2018-02-17 12:08 UTC
***Expected Behavior***

The app should stop it's noise when making or receiving a Call. It should also stop making its noise when opening a media file.

***Actual Behavior***

It keeps making its noise irrespective of incoming or outgoing calls. It also interferes on audio and music 

***Test Tools**
* Operating system : Android 6.0
* Phone : Infinix hot s
* Signal Generator App version 1.15

***How to produce the bug***

Open the app, Select any audible frequency, minimise the app and place a call. It would stop its noise for few seconds and start again to interfere with the call 

*Recording of the bug is shown below......*

https://youtu.be/ZaIL2WbldQM

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/interference-of-the-signal-generator-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by billthefarmer** [comment] 2018-02-17 12:51
This is as designed behaviour, see #2. The app is specifically designed to run in the background so it can be used for testing other apps. The wake  lock feature also allows it to keep going with the screen off. If you don't want this, stop the app using the Overview button and remove the app, or mute it with the mute button.

I will investigate muting the app during phone calls.

**Comment by billthefarmer** [comment] 2018-02-18 10:41
I have tested a [PhoneStateListener](https://developer.android.com/reference/android/telephony/PhoneStateListener.html#onCallStateChanged(int,%20java.lang.String)), which does not require the [READ_PHONE_STATE](https://developer.android.com/reference/android/Manifest.permission.html#READ_PHONE_STATE) permission. This detects incoming and outgoing calls and sets the mute.

I don't want to add the READ_PHONE_STATE permission to the app because the whole point of FOSS apps is not to ask for unnecessary permissions and annoy users.

That will be in the next version.

**Closed** 2018-03-15 14:45 UTC
